### ISSUE TITLE
expand command

### ISSUE THREAD

**Issue by jeremyj** [jpmens/mqtt-launcher#11]
Hi,

From the command line I'm doing this:
```
~$ mosquitto_pub -h localhost -t test/$(hostname)/clients_connected -m $(mosquitto_sub -h localhost -C 1 -t \$SYS/broker/clients/connected)
```
```
~$ mosquitto_sub -t test/# -h localhost -v
test/revo/clients_connected 1
```

Is there a way to get it working in the config file?

I tried this:
```
"launcher/mosquitto":{
  'local':[
     'mosquitto_pub',
     '-h',
     'localhost',
     '-t',
     'status/$(hostname)/clients_connected',
     '-m',
     '$(mosquitto_sub -h localhost -C 1 -t \$SYS/broker/clients/connected)'
  ],
```
but the commands don't get expanded:
```
~$ mosquitto_sub -h localhost -t status/# -v
status/$(hostname)/clients_connected $(mosquitto_sub -h localhost -C 1 -t \$SYS/broker/clients/connected)
```

**Comment by jpmens** [comment]
I think we use `exec()` and not shell, so no, that wouldn't work.

If you'll pardon my question? What on earth are you doing? ;-) A subscribe when a publish occurs in order to publish it? I had to wrap my head around that one ...

What are you attempting to accomplish?

**Comment by jeremyj** [comment]
@jpmens I can understand your confusion :-)
I have this setup:
```
remote clients -> remote broker 1 <--bridge--> local broker
remote clients -> remote broker 2 <--bridge--> local broker
remote clients -> remote broker 3 <--bridge--> local broker
```
The assumption is that I cannot query the remote brokers directly (nor do I want to since I would like the setup to be agnostic).

I need to know from my local broker how many clients are connected to each of my remote brokers.

With my "twisted" setup I issue a ```publish``` on my local broker which is bridged to all my remote brokers so that mqtt-launcher queries the remote brokers locally and publishes the results on an identifiable topic which is then bridged back to my local broker.

I tried configuring mqtt-launcher with a ```local``` payload that triggers a ```mosquitto_sub -t $SYS/broker/clients/connected``` on the remote broker and reading the output from the ```report``` topic on the local broker. But I have no way of associating the output to the remote broker.

I pretty new to MQTT so I'm sure there's a better way of doing this. Any suggestion would be much appreciated :-)

**Comment by jpmens** [comment]
My head hurts. :-)

I think this is the main sentence:
> I need to know from my local broker how many clients are connected to each of my remote brokers.

What I'd do is brigde **in** the appropriate `$SYS/` branch of the remote broker into a broker-specific branch on your local broker; you can then query the values locally. Look around this topic

```
$SYS/broker/clients/connected 751
```

**Comment by jeremyj** [comment]
Ah, I totally overlooked topic remapping.
Thanks for the tip!
