### ISSUE TITLE
Running ssh does not work

### ISSUE THREAD

**Issue by CodingSpiderFox** [jpmens/mqtt-launcher#12]
I want to shut down my QNAP NAS remotely via SSH using your python script (thanks! it already works great for waking that NAS up via wakeonlan)

This is my config: 

```
logfile         = '/home/user/mqtt-launcher/logfile'
mqtt_broker     = 'broker'       # default: 'localhost'. If using TLS, this must be set to the domain name signed by$
mqtt_port       = 1883              # default: 1883
mqtt_clientid   = 'mqtt-launcher-1-nas-poweroff'
mqtt_username   = ''
mqtt_password   = ''
mqtt_tls        = None              # default: No TLS

topiclist = {

    # topic                     payload value       program & arguments
	"nas/off"	:	{
					'0'	:	[ 'ssh -i /home/user/.ssh/ssh_privatekey user@nas-hostname /share/homes/admin/shutdown.sh', '' ],
				}
}
```

When I run `'ssh -i /home/user/.ssh/ssh_privatekey admin@nas /share/homes/admin/shutdown.sh` directly from the command line, it works. But with mqtt-launcher, I had no success yet.

Here is an excerpt from the logs (you can see I tried passing the script as an argument in the second attempt). But in both cases, nothing happens.
```
2018-12-15 17:32:31,193 nas/off 1 0
2018-12-15 17:32:31,194 Running t=nas/off: ['ssh -i /home/user/.ssh/ssh_privatekey admin@nas /share/homes/admin/shutdown.sh', '']
2018-12-15 17:33:15,374 Starting
2018-12-15 17:33:15,375 DEBUG MODE
2018-12-15 17:33:15,662 Connected to MQTT broker, subscribing to topics...
2018-12-15 17:33:15,820 nas/off 1 0
2018-12-15 17:33:15,822 Running t=nas/off: ['ssh -i /home/user/.ssh/ssh_privatekey admin@nas', '/share/homes/admin/shutdown.sh']
```

**Comment by jpmens** [comment]
This is definitely not an `mqtt-launcher` issue.

You might want to add `-t` to ssh; maybe your shutdown requires a tty.

**Comment by CodingSpiderFox** [comment]
Thanks, I'll try that. 

But what would be the actual difference of the command when program and arguments are

a)

`[ 'ssh -i /home/user/.ssh/ssh_privatekey user@nas-hostname /share/homes/admin/shutdown.sh', '' ]`

or b)

`[ 'ssh -i /home/user/.ssh/ssh_privatekey user@nas-hostname' ,'/share/homes/admin/shutdown.sh' ]`

Wouldn't it be equal?

**Comment by jpmens** [comment]
Look at the examples in the README; each argument is separate, so in your example you'd need

```
[ 'ssh', '-i', '....', 'user@nas', .......
]
```

**Comment by CodingSpiderFox** [comment]
Yes, it seems that it worked
