### ISSUE TITLE
Fails when run in Background

### ISSUE THREAD

**Issue by sargent-penguin** [jpmens/mqtt-launcher#14]
Probably my fault, I hope you can help.
When I run MQTT-launcher via the terminal it works well and it reports the output of the shell script I run with it.
But when I try to run it in background (with disown - I know its, bad..) it always fails with `*****> Command 'MYCOMAND' returned non-zero exit status 1`
I looked into this python problem and tried to solve it myself (subprocess, path), but none of my attempts worked..

Or is there a better way to run it in background?
Unrelated question: Does mqttwarn have this very helpful report function, where it responds with the output of the command? Because that would make me switch to mqttwarn for my purpose.

I hope you can help me.

**Comment by jpmens** [comment]
What is the program you are trying to run? It appears to be that which fails:

```
Command 'MYCOMAND' returned non-zero exit status 1
```

**Comment by sargent-penguin** [comment]
Its a bash script that runs docker exec to control my docker containers.

**Comment by jpmens** [comment]
And if you run that with disown?

**Comment by sargent-penguin** [comment]
Yeah thats the problem.
Docker commands can only be run by the root user..
Thanks for leading me in the right direction!

I will put mqtt-launcher in my docker container to run the commands there.

**Comment by jpmens** [comment]
You should be able to add yourself (well, root can) to the docker group.
