### ISSUE TITLE
double subcription on startup

### ISSUE THREAD

**Issue by inos-github** [jpmens/mqtt-launcher#15]
starting the program, the client subscribes twice to the topics. This leads to a repeated execution of commands for retained messages.

 subscription is done in on_connect(...) and again in line 154

**Comment by jpmens** [comment]
A double subscribe should have no effect. However, retained messages will, obviouisly, re-execute because we don't filter out messages with a `retain` flag.

**Comment by inos-github** [comment]
thanks for your explanation. Is there any reason for subscribing twice? or better asked the other way around: is there any negative side effect if I remove the second subscription in line 154/155?

**Comment by jpmens** [comment]
There is no reason, and I'm not sure how that slipped in. You should be able to safely remove 154/155, and I'll accept a PR for it. :-)
