### ISSUE TITLE
Use @!@ as a substring instead of a parameter

### ISSUE THREAD

**Issue by inos-github** [jpmens/mqtt-launcher#17]
Is there a way to use the value of a message as a sub-string of a command parameter?
As far as I can see, @!@ is always a parameter by it's own however I need to append a string to this value... The tool might be much more flexible with this option.

My use case:
the value of a message is a IP address and I have to append a port like ´10.0.0.1:222'
 
My suggestion:
instead of
```
87           cmd = []
88           for p in topiclist[topic][None]:
89                if p == '@!@':
90                    p = param
91                    cmd.append(p)
```
```
87            cmd = [p.replace('@!@', param) for p in topiclist[topic][None]]
```

**Comment by jpmens** [comment]
Sounds reasonable, and I'll take a pull request if you please make sure existing functionality isn't broken and the PR contains examples in the README.
