### ISSUE TITLE
Execute sudo command

### ISSUE THREAD

**Issue by marima84** [jpmens/mqtt-launcher#19]
Hi,
thank you for your code it's truly what i was looking for. My only question is if it is possible to execute a program that require sudo privileges through an mqtt payload. I've tried quite a lot but with any success.
Thank you

Mark

**Comment by jpmens** [comment]
It's likely possible, but you'd have to convince sudo to not require a console (tty). There's a `!requiretty` switch you define for that particular user somewhere in the `sudoers` file. You **must** read the sudo/sudoers manual, please, and determine whether that is a security issue for you or not.
