### ISSUE TITLE
Difficulty running python script with mqtt-launcher

### ISSUE THREAD

**Issue by derekwacks** [jpmens/mqtt-launcher#21]
Hello! 

In launcher.conf I've written:
```
    "test/message"      :   {
                               'keith2'            :   [ "/home/pi/Documents",
                                                      'python',
                                                      'keith1.py'],
                            }
```
I've also tried `[ "/home/pi/Documents", '/usr/bin/python', 'keith1.py']`

And when I publish "keith2" on the topic test/message I see in the log 
`Running t=test/message: ['/home/pi/Documents', 'python', 'keith1.py']
`
Yet the python script doesn't run? It runs properly if executed manually in the command line. 

Is there a silly error I could be making?

I've posted keith1.py below; the general context is using pyvisa to send commands through Rs232 from a Raspberry Pi to a Keithley 2401 sourcemeter, and running the .py script remotely over MQTT from another machine on the same topic thread 

```
import visa 
import time 
rm = visa.ResourceManager('@py') 
address = "ASRL/dev/ttyUSB0::INSTR"
inst = rm.open_resource(address) 
inst.write("*RST") print(inst.query("*IDN?")) 
inst.write("FORM:DATA ASCII") 
inst.write(“:SYSt:BEEP 100, 3“)
inst.close()
```

Thank you! 

Raspbian GNU/Linux 10
Python 2.7

**Comment by jpmens** [comment]
Your array of arguments seems wrong to me .. What is `"/home/pi/Documents",` supposed to represent? It should be the program you want to run, i.e. `python`.

**Comment by derekwacks** [comment]
That's it! I switched the order... `/home/pi/Documents/keith1.py is the path to the script. I'm out of the lab but can try it tomorrow morning.

Thank you so much!

**Comment by derekwacks** [comment]
@jpmens Still no luck running [ "/usr/bin/python", '/home/pi/Documents/keith1.py']

**Comment by jpmens** [comment]
check permissions, ensure that the libraries you use don't require a TTY, etc. 
Add a file creation in your program to prove that the program is run. If it is, it's then up to you, I'm afraid.

**Comment by derekwacks** [comment]
I wrote a tester but to no avail; 
```
print("Hi there.")
name = "pi/home/Documents/hello.txt"
#path = 'pi/home/Documents'
#compl = os.path.join(path, name)
#f = open(compl,"w+")
f = open(name, "w+")
for i in range(2)
        f.write("Check %d\r\n" % (i+1))
f.close()
```
at     `"test/message"      :   { 'h'            :   ["usr/bin/python", 'home/pi/Documents/hi.py'], }`
and receiving `Running t=test/message: ['usr/bin/python', 'home/pi/Documents/hi.py']`
but no file creation. 
`~/Documents` has full drwxrwxrwx

**Comment by jpmens** [comment]
You're attempting to write to a file called `pi/home/Documents/hello.txt` not knowing exactly whether that path exists (because you don't know what the invoker's current directory is).

Use something predictable and something in which any process can write, such as `/tmp/my.file.abc` and try again. Then check that file (whom does it belong to, how's it been created (permissions)) and try figuring out what the issue is.

**Comment by stvnmbr1** [comment]
i fixed it by creating a separate folder inside the root structure and setting correct permissions and owner the scripts. Anything inside the home folder doesn't work for me.
If you need need sudo you could add sudo path first
