### ISSUE TITLE
"Command returned non-zero exit status 2"

### ISSUE THREAD

**Issue by svenove** [jpmens/mqtt-launcher#22]
I'm not sure if the issue is with mqtt-launcher or with https://github.com/haim0n/python-mirobo.
My conf-file:
```
logfile         = 'logfile'
mqtt_broker     = 'localhost'       # default: 'localhost'. If using TLS, this must be set to the domain name signed by your TLS certificate.
mqtt_port       = 1883              # default: 1883
mqtt_clientid   = 'mqtt-launcher-1'
mqtt_username   = 'user'
mqtt_password   = 'password'
mqtt_tls        = None              # default: No TLS

topiclist = {

    # topic                     payload value       program & arguments
    "vacuum/control"          :   {
                                'start'        :   [ '/usr/local/bin/mirobo', '--ip 192.168.1.10', '--token 000000', 'start' ],
                                'home'          :   [ '/usr/local/bin/miiocli', 'vacuum', '--ip 192.168.1.10', '--token 000000', 'home' ],
                            },
}
```

vacuum/control/reports prints:
> *****> Command '['/usr/local/bin/mirobo', '--ip 192.168.1.10', '--token 000000', 'start']' returned non-zero exit status 2

As you can see, I've tried both "mirobo" and "miiocli", same results.
If I copy the command and run it manually, it works.

Any idea? 
Can I somehow see the output of the command, not jsut the exit status? That might help me in the right direction...

**Comment by jpmens** [comment]
These arguments look incorrect to me: `'--ip 192.168.1.10'`

It's likely they have to be separate: `'--ip', '192.168.1.10'`

There are several of them in your examples.

**Comment by svenove** [comment]
Wow, that must be a world record in responding to issues! :D
And, you was absolutely right - putting each "word" as a separate parameter seems to have done the trick!

So. where's the "donation-button"? I really love your script (and quick support)! :)
