### ISSUE TITLE
What causes this loop?

### ISSUE THREAD

**Issue by henfri** [jpmens/mqtt-launcher#26]
Hello,

for some reason, I get a loop:

> henfri@raspberrypi:~$ tail -f /var/log/mqtt-launcher.log
> 2020-03-17 20:15:18,930 DEBUG MODE
> 2020-03-17 20:15:49,947 Starting
> 2020-03-17 20:15:49,950 DEBUG MODE
> 2020-03-17 20:16:20,937 Starting
> 2020-03-17 20:16:20,940 DEBUG MODE
> 2020-03-17 20:16:21,003 Connected to MQTT broker, subscribing to topics...
> 2020-03-17 20:16:21,022 Device/action 1 unlock
> 2020-03-17 20:16:21,030 Running t=Device/action: ['/usr/local/bin/Device_launcher.sh', 'unlock']
> 2020-03-17 20:17:26,546 Device/action 1 lock
> 2020-03-17 20:17:26,550 Running t=Device/action: ['/usr/local/bin/Device_launcher.sh', 'lock']
> 2020-03-17 20:18:20,369 Device/action 1 lock
> 2020-03-17 20:18:20,373 Running t=Device/action: ['/usr/local/bin/Device_launcher.sh', 'lock']

This repeats again and again. 
But this is not caused by a command coming via mqtt. Monitoring at the same time:
```
root@homeserver:~# mosquitto_sub -h localhost -t "#" -v -u henfri -P xxxx | grep Device
Device/action lock
Device/action lock
Device/action/report MOVING
Device/action/report MOVING
```

What could cause these repeating messages?

Greetings,
Hendrik

**Comment by jpmens** [comment]
I doubt this is related to mqtt-launcher.
