### ISSUE TITLE
Keepalive, timeout and client disconnection

### ISSUE THREAD

**Issue by chdexpert** [jpmens/mqtt-launcher#29]
Hi there ! 
Thanks for your package ! It is awesome and of great help

I'm having an issue where in the case of a long process, I run into client disconnection
I receive this error
`Client mqtt-launcher-1 has exceeded timeout, disconnecting`

I believe it has to do with the PINGREQ, PINGRESP that are not sent while the process is run.
I have set the keepalive value of mqttc.connect to 65535, but I'm not sure it is viable...

Do you have any idea on how to send back a PINGREQ from the mqtt-launcher while a process is running ?

I also thought of running multiple python instances of the launcher, again a workaround and not very scalable

Thanks in advance and again thank you for your work

Edit : Simply put, how to reconnect if my process takes longer than the keepalive interval ?

**Comment by jpmens** [comment]
You'd probably have to replace the current `subprocess.check_output` by `Popen` or similar call; that's the only thing I can think of on the spur of the moment.

**Comment by chdexpert** [comment]
What difference would that imply ?

**Comment by chdexpert** [comment]
Popen(cmd, creationflags=CREATE_NEW_CONSOLE)

Perfect ! Thanks !!!
