### ISSUE TITLE
transfer number from topic to exec

### ISSUE THREAD

**Issue by leranp** [jpmens/mqtt-launcher#31]
Hi,
Thank you for this script,
it is possible to transfer a value from the topic to the exec?
for example:

topiclist = {

    # topic                     payload value       program & arguments
    "exec_switcher"          :   {
                                'value'        :   [ "/usr/bin/python2", '/home/switcher.py',"value"],
                            },
}

the topic will be for example  exec_switcher and the payload: **11**  and the exec will be /home/switcher.py **11**
is there any option for this?

**Comment by jpmens** [comment]
It is documented in the README.

**Comment by leranp** [comment]
> It is documented in the README.

Sorry, me mistake
