### ISSUE TITLE
Not a real issue - more a problem - maybe depends on Subprocess - Killall does not work in MQTT Command.

### ISSUE THREAD

**Issue by chr2002qw** [jpmens/mqtt-launcher#33]
Hello,

iam starting a script "cam.sh" with the MQTT launcher. This works fine and the script is running. Topic /camera/on
Now i want to kill that script using "killall -9 cam.sh" with Topic /camera/off.

But /report always shows "returned non-zero exit status 1" and the script is not killed.

I tryed the full Path to killall, too. An tried it with a second bash script containing the killall command. But nothing works.
Does Python Subprocess not allow to kill a process from another subprocess ?

Why i cant use killall -9 with the mqtt-launcher ?

**Comment by jpmens** [comment]
I doubt this has to do with Python. While your cam.sh is running, what does your killall report from another terminal session? (Also try pkill if you have it.)

**Comment by chr2002qw** [comment]
From terminal i can use killall -9 cam.sh and the process is killed.

**Comment by jpmens** [comment]
Are you doing this as the same user which is doing it in mqtt-launcher?

**Comment by chr2002qw** [comment]
Yes, mqtt-launcher is running in a terminal session as user "pi". For testing i killed cam.sh with a second Terminal as user "pi".

**Comment by jpmens** [comment]
show me the launcher configuration, please.

**Comment by chr2002qw** [comment]
logfile         = '/tmp/mqtt-launcher.log'
mqtt_broker     = 'xxx'       # default: 'localhost'. If using TLS, this must be set to the domain name signed by your TLS certificate.
mqtt_port       = 2188              # default: 1883
mqtt_clientid   = 'mqtt-launcher-1'
mqtt_username   = 'xxxx'
mqtt_password   = 'xxxx'
mqtt_tls        = True              # default: No TLS
# mqtt_username = 'jane'
# mqtt_password = 'secret'

topiclist = {

    # topic                     payload value       program & arguments
    "camera/power/set"  :   {
                                'ON'            :   [ '/home/pi/cam.sh' ],
                                'OFF'           :   [ '/usr/bin/killall', '-9', 'cam.sh' ],
                                'info'          :   [ '/usr/bin/touch', '/tmp/test' ],
                            },
    "prog/pwd"          :   {
                                None            :   [ 'pwd' ],
                            },
    "dev/1"             :   {
                                None            :   [ '/home/pi/cam.sh' ],
                            },
    "dev/2"             :   {
                                None            :   [ "/bin/echo", "111", "*", "@!@", "222", "@!@", "333" ],
                            },
    "dev/3"             :   {
                                None            :   [ "/bin/sh", '-c', 'var=@!@; echo $var'],
                            },
    "dev/4"             :   {
                                None            :   [ "/bin/bash",
                                                      '-c',
                                                      'IFS="/" read -r var1 var2 <<< "@!@"; echo "var1=$var1 var2=$var2"'],
                            },
}

**Comment by chr2002qw** [comment]
I tried to fire a second script with OFF comand. /home/pi/camoff with "/usr/bin/killall -9 cam.sh" But this gives the same error. So i think its not config related. Perhaps somekind of permissions between subprocesses ?

**Comment by chr2002qw** [comment]
I think, mqtt-laucher cannot be uses for running scripts like mine. My cam.sh contains a while loop to start raspistill every 5 seconds and send the payload via mqtt. 
If mqtt-launcher runs this script, it does not accept any other commands. Now i fired cam.sh on shell and send the OFF command and the process was killed.

**Comment by chr2002qw** [comment]
Solved it by somekind "dirty" way ;-) I need a second instance to fire the kill command using the same topic but diffrent payloads.
Instance 1 is listening for Payload ON  and Instance 2 is listening for Payload OFF ^^

**Comment by jpmens** [comment]
Hmm. Too many moving parts, IMO, but if it works for you ...

I'd have tried nohup(1) or the likes before doing that.

**Comment by chr2002qw** [comment]
Using nohup doesnt work, too. The Launcher Instance still got stuck in the cam.sh process. After killing cam.sh with another instance of mqtt-launcher the first instance can run commands again.
