### ISSUE TITLE
Script work under Windows with Python

### ISSUE THREAD

**Issue by ArhAngeL3000** [jpmens/mqtt-launcher#37]
Good day!
Thank you very much for your work.

I have never studied programming, this is just my hobby.
Now I am learning a smart home with MQTT and want to control my home computer.

I have successfully run your script in Windows 10 with python, but I can't figure out which command syntax to use to execute .exe or .bat files when getting certain values ​​in topics.

Can you tell me how to solve this issue?

**Comment by jpmens** [comment]
Good question. It's likely going to be something like this in the program arguments bit of the configuration (compare with the README.md):

```
[ 'cmd.exe', '/c', '/path/to/my.bat' ],
```

You're going to have to check the syntax of `cmd.exe` (I'm doing this from what I remember was 20y ago :-)

**Comment by ArhAngeL3000** [comment]
Thanks for the quick response!
I tried your version, and several others.

No results so far. I will describe the options below. With the first, nothing simply happens, and with the other two, the script does not run at all.

`topiclist = {

    # topic                     payload value       program & arguments
    "infierno/switch" :	{
									'1'			:   [ 'cmd.exe', '/c', "C:/Users/messe/Desktop/MQTTLauncher/hello.bat" ],
									#'2'			:	[ 'from subprocess import Popen', 'p = Popen("hello.bat", cwd=r"C:\Users\messe\Desktop\MQTTLauncher")' ],
									#'3'			:	[ 'p = subprocess.Popen("C:\\Users\\messe\\Desktop\\MQTTLauncher\\hello.bat assembleRelease", cwd="C:\\Users\\messe\\Desktop\\MQTTLauncher\\", creationflags=subprocess.CREATE_NEW_CONSOLE)' ],
                        },
}`

**Comment by jpmens** [comment]
You are trying to execute Python code in `#2` and `#3`. That cannot work.

**Comment by jpmens** [comment]
Have you tried

```
[  "C:/Users/messe/Desktop/MQTTLauncher/hello.bat" ],
```

**Comment by ArhAngeL3000** [comment]
Yes, I tried it.
The log file displays a line and nothing happens.

`Running t=infierno/switch: ['C:/Users/messe/Desktop/MQTTLauncher/hello.bat']`

**Comment by ArhAngeL3000** [comment]
Good day!
I thought that the Python language cannot be used in the commands of the configuration file. Is it possible to make links to lines of code in the mqtt-launcher.py script itself?
Then it will be possible to run .bat files using Python syntax?

**Comment by jpmens** [comment]
No, neither is possible. Of course if you are able to you can alter your version of `mqtt-launcher` to provide that capability. 

I don't think anybody's ever tried to do this on Windows (I certainly have not), so unfortunately you're on your own. Good luck.

**Comment by ArhAngeL3000** [comment]
OK.
Thanks for the help!
I will look for other solutions.
