### ISSUE TITLE
json support

### ISSUE THREAD

**Issue by clach04** [jpmens/mqtt-launcher#39]
I have a branch with json support https://github.com/clach04/mqtt-launcher/tree/json_config rather than Python code for config.

1. Any interest in this as a feature? If so, as an additional format or as a replacement for Python - I don't yet have code to support both but it could be done
2. For Python config support, any thoughts about supporting functions as well as spawning sub-processes? (I do not have code for this :-D)

**Comment by jpmens** [comment]
Thanks for asking.

1. no specific interest, as I don't see how that benefits anybody as it IMO doesn't ease configuration. Would you care to elaborate on the reasons for doing this?
2. I've not thought about this because `mqtt-launcher` basically was just an experiment. If you felt like working on this, I'd take a PR for it; sounds good.

In view of 2. why implement 1.? :-)

**Comment by clach04** [comment]
One advantage of the config file not being executable code is that any config errors that cause the launcher to fail are more likey to happen at load time, rather than some execution code that might happen later when executed that take the server down. Its definitely a style thing, either way something will be executed under user control so trust is needed in either scenario.

For #2- I'm not sure... I've been surprised how many times I didn't write a full python app and used mqtt-launcher instead as an experiment and then leaving that experiment running all the time :-D I'm still thinking about the implications of that idea.

Right now I'm using my json-config fork (with a service, its all bundled together so I'd need to clean separate that with individual PRs so I need to find the energy to do it, hence asking first!)

Thanks for making this available, it's been great for quick experiments!

**Comment by jpmens** [comment]
Closing for now.
