### ISSUE TITLE
No matching param (OFF) for sound/1/set/report

### ISSUE THREAD

**Issue by ways** [jpmens/mqtt-launcher#5]
Hi

I've set up mqtt-launcher to play a sound, but it seems it keeps crashing and I'm having trouble understanding this error.

launcher.conf:

> "sound/1/set/report" : {
>     'state' : [ 'echo', '"OFF"' ],
>  },
>  "sound/1/set" : {
>     'OFF'   : [ '/home/pi/mqtt-launcher/buzzset.sh', '1', '0' ],
>     'ON'    : [ '/home/pi/mqtt-launcher/buzzset.sh', '1', '1' ],
>  },

In home-assistant (may be relevant):

> - platform: mqtt
>   name: "Buzzer bop"
>   state_topic: "sound/1/set/report"
>   command_topic: "sound/1/set"
>   payload_on: "ON"
>   payload_off: "OFF"
>   optimistic: false
>   qos: 0
>   retain: false

mqtt shows:

> clients/mqtt-launcher Adios!
> sound/1/set/report OFF
> clients/mqtt-launcher Adios!
> clients/mqtt-launcher Adios!

mqtt-launchers log says:

> 2017-08-30 14:31:54,122 Connected to MQTT broker, subscribing to topics...
> 2017-08-30 14:31:54,136 sound/1/set 0 OFF
> 2017-08-30 14:31:54,139 Running t=sound/1/set: ['/home/pi/mqtt-launcher/buzzset.sh', '1', '0']
> 2017-08-30 14:31:54,244 sound/1/set/report 2 OFF
> 2017-08-30 14:31:54,247 No matching param (OFF) for sound/1/set/report
> 2017-08-30 14:32:05,138 OOOOPS! launcher disconnects
> 2017-08-30 14:32:16,168 Connected to MQTT broker, subscribing to topics...
> 2017-08-30 14:32:16,182 sound/1/set 0 OFF
> 2017-08-30 14:32:16,187 Running t=sound/1/set: ['/home/pi/mqtt-launcher/buzzset.sh', '1', '0']
> 2017-08-30 14:32:16,293 sound/1/set/report 2 OFF
> 2017-08-30 14:32:16,296 No matching param (OFF) for sound/1/set/report
> 2017-08-30 14:32:27,182 OOOOPS! launcher disconnects
> 2017-08-30 14:32:38,213 Connected to MQTT broker, subscribing to topics...
> ...

**Comment by ways** [comment]
The service works, so I guess the error isn't much of a problem. The main problem is the disconnects. See the same on both my clients. Opening a separate issue for it.

**Comment by jpmens** [comment]
You're using same clientId which is being kicked by the broker; correct behaviour.
