### ISSUE TITLE
How do you get this to run a script?

### ISSUE THREAD

**Issue by 2devnull** [jpmens/mqtt-launcher#7]
e.g /root/Scripts/myscript.sh flower, I tried

`['/bin/bash', '/root/Scripts/myscript.sh', 'flower']`

and 

`['/root/Scripts/myscript.sh', 'flower']`

But it doesn't call the script

**Comment by 2devnull** [comment]
I see this in /report

`*****> [Errno 2] No such file or directory`

**Comment by 2devnull** [comment]
Well, I changed shell=True, but now get this error in /report:

`*****> Command '['/root/Scripts/myscript.sh', 'flower']' returned non-zero exit status 127`

The script runs find from the command line directly

**Comment by jpmens** [comment]
Show your configuration file

**Comment by 2devnull** [comment]
This may have been my error of a spelling mistake. Anyway, I wrote a simple bash script instead to do the subscription to get around the problem and it is working well for my limited purpose. 

Thanks.
