### ISSUE TITLE
Script only executed once

### ISSUE THREAD

**Issue by hermannw** [jpmens/mqtt-launcher#8]
Hi JP
first I would like to thank you for sharing this program!
It works great with the example configuration but not so much with mine.
Here is my configuration:
```
logfile = 'logfile'
mqtt_broker = '192.168.1.120'       # default: 'localhost'
mqtt_port = 1883                # default: 1883
mqtt_clientid = 'mqtt-launcher-1'
mqtt_username = ''
mqtt_password = ''

topiclist = {

    # topic                     payload value       program & arguments
    "dak/screen"          :   {
                                'off' :   [ '/home/pi/ir_scripts/rpi-hdmi.sh', 'off' ],
                                'on'  :   [ '/home/pi/ir_scripts/rpi-hdmi.sh', 'on'],
                               },
}
```
I start mqtt-launcher from the command line as user pi.
Then I send (from Node-Red) Topic: dak/screen Payload: on (QoS 2, Retain false) which works ok.
Then I send  Topic: dak/screen Payload: off which usually works too (but not always) but then no other commands are accepted. No matter what I send, it is just ignored. Nothing shows up in the log.
But obviously the commands I send are stored somewhere because when I stop mqtt-launcher and start it again, all the previous commands are executed immediately.
```
2018-02-24 12:16:03,827 Starting
2018-02-24 12:16:03,829 DEBUG MODE
2018-02-24 12:16:03,848 Connected to MQTT broker, subscribing to topics...
2018-02-24 12:16:11,637 dak/screen 2 on
2018-02-24 12:16:11,645 Running t=dak/screen: ['/home/pi/ir_scripts/rpi-hdmi.sh', 'on']
--- This time only one command was executed
2018-02-24 12:18:33,811 Starting
2018-02-24 12:18:33,813 DEBUG MODE
2018-02-24 12:18:33,830 Connected to MQTT broker, subscribing to topics...
2018-02-24 12:18:33,925 dak/screen 2 off
2018-02-24 12:18:33,931 Running t=dak/screen: ['/home/pi/ir_scripts/rpi-hdmi.sh', 'off']
2018-02-24 12:18:34,063 display_power=0
2018-02-24 12:18:34,072 dak/screen 2 on
2018-02-24 12:18:34,075 Running t=dak/screen: ['/home/pi/ir_scripts/rpi-hdmi.sh', 'on']
---After restart all the previously sent commands are executed
```
Any idea what is going wrong here?

Hermann

**Comment by jpmens** [comment]
Something rings a _very vague_ bell (independently of mqtt-launcher) ... but I cannot grasp it.

Have you verified you don't have another client connected to your broker with the same MQTT clientId? (ClientIDs must be unique on a broker and strange things happen such as the broker kicking one then the other off before they reconnect)

Another thing to check: what version of Mosquitto are you using? Something really old?

**Comment by jpmens** [comment]
Also, make sure you run a `mosquitto_sub -h 192.168.1.120 -v -t 'dak/#'` against your broker on a 2nd terminal to watch what Node-Red is sending you

**Comment by hermannw** [comment]
Yes I learned about the ClientID the hard way. It took me quite a while to find out that two of my ESP8266 were using the same ID. So this is one of the first things I make sure.
The installation of this Pi Zero is fairly new. I am only running it for about six month. How can you check the version of Mosquitto? I just tried to do an update and got an error message from the Mosquitto repository. Got to check that...

I also made sure that MQTT messages were coming in as they should.

**Comment by hermannw** [comment]
After a few hours of searching I tracked the problem back to this line:
```
export DISPLAY=:0.0 && kweb -KHJEYPA+-rmfk http://dakboard.com/app?p=b5.... &
```
This line is starting an instance of kweb browser on the attached monitor.
I have no idea why, but when this line is executed from within my script or from a script started by my script, it brakes the connection between mqtt-launcher (paho?) and mosquitto. When this line is executed after my script is done, everything works. So I made a workaround to execute this line from a cronjob a minute later...

Hermann

**Comment by jpmens** [comment]
I'm not at all familiar with that or with what it does, but that doesn't matter. 

If you were doing that from withing the `rpi-hdmi` script, then what's probably happening is that the controlling tty is being held open; you could try running that with `nohup(1)`.

**Comment by hermannw** [comment]
Nope. Didn't do it.
Nonetheless, thank you for your help.
I'll keep trying.

Hermann

**Comment by jpmens** [comment]
So you are manipulating Mac power with this, am I understanding it correctly? I hope you don't expect me to debug what happens when you change power settings on the fly ...

Please provide a simple example with which I can reproduce the problem.
