### ISSUE TITLE
TLS support in mqtt-launcher? 

### ISSUE THREAD

**Issue by thecalle** [jpmens/mqtt-launcher#9]
Hi.
Can https or wss be enabled in client? Is it possible to mask login and pwd data to avoid someone can stole them?

**Comment by jpmens** [comment]
If you configure TLS in your client and set up `mqtt-launcher` to support it, then sure. `mqtt-launcher` doesn't have support for TLS, but that's pretty easy to accomplish.

**Comment by hagenbauer** [comment]
I am trying to setup mqtt-launcher with tls. Unfortunally I do not see the necessary parameters in the config example. how could I configure it?

**Comment by jpmens** [comment]
Maybe I misunderstood OP's question. mqtt-launcher has no support for TLS but it's easy to add. PR accepted. :-)

**Comment by hagenbauer** [comment]
I would love too but I have no idea. I could solve this via bash scripting https://www.hagen-bauer.de/2018/03/MQTT-Commander.html

**Comment by jpmens** [comment]
TLS support was added via #10
